### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by maniaabdi** [1a1a11a/PyMimircache#13]
Hi 

I am trying to compute the hit ratio for a trace set I have. I played with the example of tutorial and my sense is that the simulator works with fixed object sizes. I read over the "Dynamic Performance Profiling of Cloud Caches" paper and the variable object size could be added as an extension.  I was wondering if the variable object size is supported by the current version of the simulator.

Regards
Mania

**Comment by 1a1a11a** [comment]
Hi Mania, the current version only supports fix-sized object, but the next version will support variable sized object, expect the next version to be out before end of March.

**Comment by maniaabdi** [comment]
Thanks Jason for your reply.
