### ISSUE TITLE
problem during install pymimircache

### ISSUE THREAD

**Issue by youngeryoungeryang** [1a1a11a/PyMimircache#16]
Hi,

I install PyMimircache follow the README.md, when I execute ' sudo pip3 install PyMimircache',
 it says that 'CMimircache is not successfully installed, modules beginning with C are all disabled',
and when I run a test program, it falls with information of 
'  File "open_file.py", line 1, in <module>
    from PyMimircache import Cachecow
    ModuleNotFoundError: No module named 'PyMimircache' '

I really want to know what should I do to make it run successfully

**Comment by 1a1a11a** [comment]
Can you post the full error? It looks like something went wrong in the CMimircache installation

**Comment by youngeryoungeryang** [comment]
OK.

I try to install with source code in docker, when I try to use it, it falls with the information of that:

![1](https://user-images.githubusercontent.com/45582966/118906152-c7c40780-b94f-11eb-9d85-a93785332fad.png)

**Comment by 1a1a11a** [comment]
How did you install it? There might be an error in the installation.
