### ISSUE TITLE
Cache warmup feature for hit_ratio

### ISSUE THREAD

**Issue by Jasim9** [1a1a11a/PyMimircache#5]
An option to warmup the cache with a trace and then calculate hit_ratios on a separate test trace so that if after warmup cache contains all unique keys of the test trace then MIMIR gives a 100% hit_rate. 

Currently, all unique keys in the trace cause a miss, and hence the hit-rate can never reach 100% even if the cache_size is big enough to hold all of them.

**Comment by 1a1a11a** [comment]
Thank you, Jasim9, this will be added soon. 
We are currently doing a big refactoring.

**Comment by Jasim9** [comment]
Hey Jason, was this added in the previous release? If not when can this feature be expected to be done in future?
Thanks,

**Comment by 1a1a11a** [comment]
Sorry, not yet.
